[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
social = "9BXzYsCbqFLwTzkqognW18JiZa7DrzhccsifMHSjcwxS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bash -lc 'FILE=${TEST_FILE:-tests/**/*.ts}; yarn run ts-mocha -p ./tsconfig.json -t 1000000 $FILE'"
nft_mint = "npx ts-node app/nft_mint_example.ts"
like = "npx ts-node app/like_example.ts"
